CREATE TABLE DAYS(
    NUM NUMBER PRIMARY KEY
    ,ID VARCHAR2(20) NOT NULL
    ,TITLE VARCHAR2(200) NOT NULL
    ,SDATE DATE NOT NULL
    ,EDATE DATE NOT NULL
    ,WRDATE DATE DEFAULT SYSDATE    
);

CREATE SEQUENCE DAYS_SEQ;

INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '몽몽이', '신정', '20/01/01', '20/01/01');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '굿보이', '설날', '20/01/24','20/01/27');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '롱롱', '3.1절', '20/03/01', '20/03/01');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '미녀', '국회의원 선거', '20/04/15', '20/04/15');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '홍길동', '석가탄신일', '20/04/30', '20/04/30');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '도라에몽', '어린이날', '20/05/05', '20/05/05');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '초코초코', '현충일', '20/08/15', '20/08/15');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '니혼고', '광복절', '20/06/06', '20/06/06');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '초코초코', '추석', '20/09/30', '20/10/2');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '카페라테', '개천절', '20/10/03', '20/10/03');
INSERT INTO DAYS(NUM, ID, TITLE, SDATE, EDATE) VALUES(DAYS_SEQ.NEXTVAL, '축구', '크리스마스', '20/12/25', '20/12/25');

